Feature branch - finished mint-sign up replica
Yors-git/mint-signup pull request #1
Opened 2020-08-18 08:31 UTC by Yors-git

It contains: 

- Formatted buttons at the top and in the form
- A form with inputs with appropriate types and labels
- Footer
- Proper layout of the sign up page

2020-08-18 12:15 UTC, canriquez requested changes
Hello 👋  Jorge Torres Bribiesca & Alaukik Khare. Project needs changes  ♻️
--

Good work so far in this project 👍 . 
You've produced a good read me file. Great use of  Github Flow, with good commit information and detailed pull request. Also, the page looks really good and very similar to the original. 
There are still some points to address so you can continue forward to the next project. Please work on the items below and submit a code review request when you finish ticking on the boxes in the list below.


- [x]  Add .gitignore file and include .DS_Store files. This file is not related to the project. 
![image](https://user-images.githubusercontent.com/25496166/90508509-41636680-e12e-11ea-8f9b-6eba0b3e06f1.png)

- [x] FIx label tags - input-tags patterns. Hint from [Learn to Code HTML-CSS](https://learn.shayhowe.com/html-css/building-forms/)
![image](https://user-images.githubusercontent.com/25496166/90510976-33174980-e132-11ea-91cf-c4549a76582b.png)
 

- [x] Use the specific input tag type for the requested data in the form. Hint: check the phone input tag and use the correct type for it.
![image](https://user-images.githubusercontent.com/25496166/90508866-cbabca80-e12e-11ea-9e18-0db13c84722d.png)


- [x] Fix the liner issues in this submission. The project has linter problems. Check commented code below for more hints.

OPTIONAL: You don't need to make this changes to approve this project. We encourage you to start using HTML semantic to organize HTML sections. Major navigation links could be organized using NAV tag and also main content using MAIN tags.

Again, congratulations on the progress so far.  Work on those pending things and submit a new code review request. 

All the best.
Carlos

--
Carlos Anriquez | [github](https://github.com/canriquez) | [Twitter](https://twitter.com/cranriquez) | [LinkedIn](https://www.linkedin.com/in/carlosanriquez/) | [Portfolio](https://www.carlosanriquez.com/)

2020-08-18 12:15 UTC, canriquez commented on index.html
> +        </label>
- Please use the right type for the specific input information. 
![image](https://user-images.githubusercontent.com/25496166/90510490-79b87400-e131-11ea-9ed8-71127eb2ff96.png)
hint from [w3schools.com](https://www.w3schools.com/tags/att_input_type_tel.asp)

2020-08-18 12:15 UTC, canriquez commented on index.html
> +        </label>
For all the label-input tag patterns, make sure that the for="" property in the label tag, match with an id="" property used in the input.
Hint: 
![image](https://user-images.githubusercontent.com/25496166/90510803-f3e8f880-e131-11ea-8d34-56952ac0aee2.png)

2020-08-18 13:45 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @Yors-git @newhorizon-tech** 
Good job with your new submission for this project :muscle:  :muscle:
Your page passes most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:
- [x] Don't use important
- [x] The images below the Intuit logo are not in the correct order:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/l0N5VOql.png) | ![image](https://i.imgur.com/DCQxnXGl.png) |

- [x] The input password in the form should have a lock icon:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/OTiuqVul.png) | ![image](https://i.imgur.com/y3ciziNl.png) |

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-08-18 13:45 UTC, andresporras3423 commented on styles/style.css
> +#disclaimer {
Don't overuse ID selectors

2020-08-18 16:28 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project it's looking really good, however, in order to accomplish as the actual page, you required to do these changes, listed below:
 - [ ] Your form is broken, kindly fix that.
<table>
 <tr>
 <th>Yours</th>
 <th>Original</th>
 </tr>
 <tr>
 <td><img src="https://user-images.githubusercontent.com/56762529/90539476-3d4b3f00-e156-11ea-8e56-7c447e747261.png">
</td>
 <td><img src="https://user-images.githubusercontent.com/56762529/90539577-623fb200-e156-11ea-9f4f-424b63bf6569.png"></td>
 </tr>
</table>
 
**Please make the required changes and resubmit for a new code review once you are ready**

As always, I wish you all the very best and see you both at the top🚀

  

<hr>

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-19 13:32 UTC, canriquez approved these changes
Hello 👋  Jorge Torres Bribiesca & Alaukik Khare. Project Approved!  ✅
--
Congratulations on a really well-made project. The page looks great 🎉
You have implemented all suggested changes and TSE indications. The code now is clean and complying in full with all the requirements. Also, linters look all green this time 👍.

You are now ready to go for bigger challenges!

Keep up the good work.
Best regards
Carlos

Carlos Anriquez | [github](https://github.com/canriquez) | [Twitter](https://twitter.com/cranriquez) | [LinkedIn](https://www.linkedin.com/in/carlosanriquez/) | [Portfolio](https://www.carlosanriquez.com/)

2020-08-19 13:57 UTC, merged